version: '3.8'

services:
  backend:
    build: ./backend-server
    ports:
      - "5000:5000"
    env_file:
      - ./backend-server/.env
    depends_on:
      - mongo

  website:
    build: ./website
    ports:
      - "3000:3000"
    env_file:
      - ./website/.env
    depends_on:
      - backend

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: danielessl
      MONGO_INITDB_ROOT_PASSWORD: 1a1o97XqzQV8Uz
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: