name: CI Pipeline

defaults:
    run:
        working-directory: ./backend-server

on: 
    push
        branches:
            - staging

steps:
- uses: actions/checkout@v4
- uses: actions/setup-python@v5
  with:
    python-version: '3.10' 
- run: python -m unittest tests/test_app.py
- run: python -m pip install --upgrade pip
- run: pip install -r requirements.txt
